version: "3.4"
services:

# application service
app_ml:
  container_name: skill_app_diplom
  image: app_diplom
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - logs:/usr/local/app_ml/logs
    - models:/usr/local/app_ml/models
    - dataset:/usr/local/app_ml/dataset
  restart: always
  ports:
    - 8015:8015
  networks:
    - custom

volumes:
  logs: { }
  models: { }
  dataset: { }
  prometheus_data: { }
  grafana_data: { }
networks:
  custom:
    driver: bridge
